# Use user/password credentials
version: '3.7'

services:

#  resource:
#    image: vuttr/resource
#    build: .
#    depends_on:
#      - resource_db
#    ports:
#      - 3000:3000

  oauth2:
    image: vuttr/oauth2
    build: .
    depends_on:
      - oauth2_db
    ports:
      - 8095:8095

  resource_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  oauth2_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    ports:
      - 8081:8080

